default: &default
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_unicode_ci
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("RDB_HOSTNAME") { "localhost" } %>
  username: <%= ENV.fetch("RDB_USERNAME") { "root" } %>
  password: <%= ENV.fetch("RDB_PASSWORD") { "" } %>

development:
  <<: *default
  database: symple_ats_api_development

test:
  <<: *default
  database: symple_ats_api_test

staging:
  <<: *default
  database: symple_ats_api_staging

production:
  <<: *default
  database: symple_ats_api_production
